objects = main.o tables.o savePng.o yuv.o

convert: $(objects)
	gcc -o convert -O2 -s -lm -lpng -Wall -Wextra -flto $(objects)
%.o: %.c
	gcc -O2 -s -lm -lpng -Wall -Wextra -flto -c $< -o $@
$(objects) :
.PHONY : clean
clean :
	rm convert $(objects)
