#make sure to supply the latest version of miniz.c there should be no need to modify anything
objects = main.o tables.o savePng.o yuv.o bilinear.o adaptive.o pixels.o

convert: $(objects)
	gcc -o convert -O2 -s -lm -Wall -Wextra $(objects)
%.o: %.c
	gcc -O2 -s -lm -Wall -Wextra -DUSE_MINIZ -c $< -o $@
$(objects) :
.PHONY : clean
clean :
	rm convert $(objects)
